using Microsoft.EntityFrameworkCore.Migrations;

namespace TravelExpenses.Persistence.Migrations
{
    public partial class currency_seed_data : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var inserts =
@"INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('AED', 'United Arab Emirates Dirham');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('AFN', 'Afghan Afghani');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('ALL', 'Albanian Lek');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('AMD', 'Armenian Dram');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('ANG', 'Netherlands Antillean Guilder');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('AOA', 'Angolan Kwanza');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('ARS', 'Argentine Peso');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('AUD', 'Australian Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('AWG', 'Aruban Florin');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('AZN', 'Azerbaijani Manat');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BAM', 'Bosnia-Herzegovina Convertible Mark');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BBD', 'Barbadian Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BDT', 'Bangladeshi Taka');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BGN', 'Bulgarian Lev');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BHD', 'Bahraini Dinar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BIF', 'Burundian Franc');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BMD', 'Bermudan Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BND', 'Brunei Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BOB', 'Bolivian Boliviano');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BRL', 'Brazilian Real');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BSD', 'Bahamian Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BTC', 'Bitcoin');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BTN', 'Bhutanese Ngultrum');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BWP', 'Botswanan Pula');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BYN', 'New Belarusian Ruble');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BYR', 'Belarusian Ruble');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('BZD', 'Belize Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('CAD', 'Canadian Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('CDF', 'Congolese Franc');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('CHF', 'Swiss Franc');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('CLF', 'Chilean Unit of Account (UF)');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('CLP', 'Chilean Peso');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('CNY', 'Chinese Yuan');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('COP', 'Colombian Peso');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('CRC', 'Costa Rican Colón');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('CUC', 'Cuban Convertible Peso');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('CUP', 'Cuban Peso');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('CVE', 'Cape Verdean Escudo');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('CZK', 'Czech Republic Koruna');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('DJF', 'Djiboutian Franc');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('DKK', 'Danish Krone');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('DOP', 'Dominican Peso');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('DZD', 'Algerian Dinar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('EGP', 'Egyptian Pound');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('ERN', 'Eritrean Nakfa');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('ETB', 'Ethiopian Birr');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('EUR', 'Euro');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('FJD', 'Fijian Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('FKP', 'Falkland Islands Pound');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('GBP', 'British Pound Sterling');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('GEL', 'Georgian Lari');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('GGP', 'Guernsey Pound');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('GHS', 'Ghanaian Cedi');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('GIP', 'Gibraltar Pound');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('GMD', 'Gambian Dalasi');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('GNF', 'Guinean Franc');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('GTQ', 'Guatemalan Quetzal');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('GYD', 'Guyanaese Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('HKD', 'Hong Kong Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('HNL', 'Honduran Lempira');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('HRK', 'Croatian Kuna');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('HTG', 'Haitian Gourde');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('HUF', 'Hungarian Forint');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('IDR', 'Indonesian Rupiah');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('ILS', 'Israeli New Sheqel');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('IMP', 'Manx pound');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('INR', 'Indian Rupee');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('IQD', 'Iraqi Dinar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('IRR', 'Iranian Rial');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('ISK', 'Icelandic Króna');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('JEP', 'Jersey Pound');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('JMD', 'Jamaican Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('JOD', 'Jordanian Dinar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('JPY', 'Japanese Yen');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('KES', 'Kenyan Shilling');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('KGS', 'Kyrgystani Som');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('KHR', 'Cambodian Riel');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('KMF', 'Comorian Franc');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('KPW', 'North Korean Won');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('KRW', 'South Korean Won');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('KWD', 'Kuwaiti Dinar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('KYD', 'Cayman Islands Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('KZT', 'Kazakhstani Tenge');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('LAK', 'Laotian Kip');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('LBP', 'Lebanese Pound');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('LKR', 'Sri Lankan Rupee');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('LRD', 'Liberian Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('LSL', 'Lesotho Loti');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('LTL', 'Lithuanian Litas');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('LVL', 'Latvian Lats');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('LYD', 'Libyan Dinar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('MAD', 'Moroccan Dirham');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('MDL', 'Moldovan Leu');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('MGA', 'Malagasy Ariary');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('MKD', 'Macedonian Denar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('MMK', 'Myanma Kyat');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('MNT', 'Mongolian Tugrik');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('MOP', 'Macanese Pataca');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('MRO', 'Mauritanian Ouguiya');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('MUR', 'Mauritian Rupee');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('MVR', 'Maldivian Rufiyaa');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('MWK', 'Malawian Kwacha');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('MXN', 'Mexican Peso');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('MYR', 'Malaysian Ringgit');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('MZN', 'Mozambican Metical');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('NAD', 'Namibian Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('NGN', 'Nigerian Naira');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('NIO', 'Nicaraguan Córdoba');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('NOK', 'Norwegian Krone');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('NPR', 'Nepalese Rupee');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('NZD', 'New Zealand Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('OMR', 'Omani Rial');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('PAB', 'Panamanian Balboa');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('PEN', 'Peruvian Nuevo Sol');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('PGK', 'Papua New Guinean Kina');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('PHP', 'Philippine Peso');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('PKR', 'Pakistani Rupee');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('PLN', 'Polish Zloty');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('PYG', 'Paraguayan Guarani');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('QAR', 'Qatari Rial');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('RON', 'Romanian Leu');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('RSD', 'Serbian Dinar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('RUB', 'Russian Ruble');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('RWF', 'Rwandan Franc');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('SAR', 'Saudi Riyal');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('SBD', 'Solomon Islands Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('SCR', 'Seychellois Rupee');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('SDG', 'Sudanese Pound');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('SEK', 'Swedish Krona');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('SGD', 'Singapore Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('SHP', 'Saint Helena Pound');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('SLL', 'Sierra Leonean Leone');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('SOS', 'Somali Shilling');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('SRD', 'Surinamese Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('STD', 'São Tomé and Príncipe Dobra');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('SVC', 'Salvadoran Colón');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('SYP', 'Syrian Pound');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('SZL', 'Swazi Lilangeni');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('THB', 'Thai Baht');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('TJS', 'Tajikistani Somoni');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('TMT', 'Turkmenistani Manat');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('TND', 'Tunisian Dinar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('TOP', 'Tongan Paʻanga');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('TRY', 'Turkish Lira');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('TTD', 'Trinidad and Tobago Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('TWD', 'New Taiwan Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('TZS', 'Tanzanian Shilling');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('UAH', 'Ukrainian Hryvnia');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('UGX', 'Ugandan Shilling');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('USD', 'United States Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('UYU', 'Uruguayan Peso');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('UZS', 'Uzbekistan Som');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('VEF', 'Venezuelan Bolívar Fuerte');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('VND', 'Vietnamese Dong');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('VUV', 'Vanuatu Vatu');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('WST', 'Samoan Tala');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('XAF', 'CFA Franc BEAC');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('XAG', 'Silver (troy ounce)');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('XAU', 'Gold (troy ounce)');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('XCD', 'East Caribbean Dollar');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('XDR', 'Special Drawing Rights');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('XOF', 'CFA Franc BCEAO');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('XPF', 'CFP Franc');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('YER', 'Yemeni Rial');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('ZAR', 'South African Rand');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('ZMK', 'Zambian Kwacha (pre-2013)');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('ZMW', 'Zambian Kwacha');
INSERT INTO [app].[Currency] ([IsoCode], [CurrencyName]) VALUES ('ZWL', 'Zimbabwean Dollar');
";

            migrationBuilder.Sql(inserts);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            var sql = @"DELETE FROM [app].[Currency]";
            migrationBuilder.Sql(sql);
        }
    }
}
