using Microsoft.EntityFrameworkCore.Migrations;

namespace TravelExpenses.Persistence.Migrations
{
    public partial class countries_seed_data : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var inserts =
@"INSERT INTO [app].[Country] ([CountryName]) VALUES ('Afghanistan');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Albania');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Algeria');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('American Samoa');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Andorra');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Angola');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Anguilla');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Antarctica');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Antigua and Barbuda');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Argentina');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Armenia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Aruba');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Australia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Austria');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Azerbaijan');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Bahamas');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Bahrain');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Bangladesh');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Barbados');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Belarus');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Belgium');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Belize');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Benin');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Bermuda');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Bhutan');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Bolivia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Bosnia and Herzegovina');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Botswana');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Bouvet Island');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Brazil');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('British Indian Ocean Territory');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Brunei Darussalam');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Bulgaria');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Burkina Faso');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Burundi');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Cambodia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Cameroon');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Canada');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Cape Verde');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Cayman Islands');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Central African Republic');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Chad');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Chile');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('China');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Christmas Island');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Cocos (Keeling) Islands');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Colombia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Comoros');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Congo');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Congo, the Democratic Republic of the');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Cook Islands');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Costa Rica');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Cote D''Ivoire');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Croatia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Cuba');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Cyprus');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Czech Republic');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Denmark');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Djibouti');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Dominica');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Dominican Republic');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Ecuador');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Egypt');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('El Salvador');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Equatorial Guinea');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Eritrea');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Estonia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Ethiopia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Falkland Islands (Malvinas)');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Faroe Islands');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Fiji');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Finland');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('France');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('French Guiana');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('French Polynesia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('French Southern Territories');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Gabon');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Gambia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Georgia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Germany');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Ghana');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Gibraltar');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Greece');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Greenland');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Grenada');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Guadeloupe');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Guam');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Guatemala');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Guinea');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Guinea-Bissau');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Guyana');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Haiti');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Heard Island and Mcdonald Islands');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Holy See (Vatican City State)');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Honduras');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Hong Kong');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Hungary');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Iceland');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('India');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Indonesia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Iran, Islamic Republic of');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Iraq');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Ireland');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Israel');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Italy');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Jamaica');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Japan');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Jordan');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Kazakhstan');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Kenya');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Kiribati');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Korea, Democratic People''s Republic of');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Korea, Republic of');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Kuwait');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Kyrgyzstan');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Lao People''s Democratic Republic');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Latvia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Lebanon');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Lesotho');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Liberia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Libyan Arab Jamahiriya');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Liechtenstein');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Lithuania');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Luxembourg');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Macao');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Macedonia, the Former Yugoslav Republic of');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Madagascar');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Malawi');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Malaysia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Maldives');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Mali');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Malta');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Marshall Islands');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Martinique');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Mauritania');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Mauritius');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Mayotte');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Mexico');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Micronesia, Federated States of');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Moldova, Republic of');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Monaco');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Mongolia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Montserrat');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Morocco');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Mozambique');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Myanmar');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Namibia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Nauru');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Nepal');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Netherlands');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Netherlands Antilles');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('New Caledonia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('New Zealand');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Nicaragua');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Niger');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Nigeria');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Niue');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Norfolk Island');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Northern Mariana Islands');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Norway');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Oman');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Pakistan');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Palau');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Palestinian Territory, Occupied');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Panama');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Papua New Guinea');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Paraguay');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Peru');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Philippines');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Pitcairn');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Poland');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Portugal');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Puerto Rico');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Qatar');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Reunion');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Romania');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Russian Federation');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Rwanda');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Saint Helena');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Saint Kitts and Nevis');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Saint Lucia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Saint Pierre and Miquelon');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Samoa');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('San Marino');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Sao Tome and Principe');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Saudi Arabia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Senegal');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Serbia and Montenegro');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Seychelles');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Sierra Leone');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Singapore');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Slovakia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Slovenia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Solomon Islands');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Somalia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('South Africa');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('South Georgia and the South Sandwich Islands');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Spain');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Sri Lanka');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Sudan');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Suriname');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Svalbard and Jan Mayen');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Swaziland');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Sweden');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Switzerland');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Syrian Arab Republic');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Taiwan, Province of China');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Tajikistan');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Tanzania, United Republic of');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Thailand');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Timor-Leste');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Togo');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Tokelau');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Tonga');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Trinidad and Tobago');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Tunisia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Turkey');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Turkmenistan');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Turks and Caicos Islands');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Tuvalu');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Uganda');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Ukraine');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('United Arab Emirates');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('United Kingdom');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('United States');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('United States Minor Outlying Islands');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Uruguay');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Uzbekistan');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Vanuatu');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Venezuela');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Viet Nam');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Virgin Islands, British');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Virgin Islands, U.s.');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Wallis and Futuna');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Western Sahara');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Yemen');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Zambia');
INSERT INTO [app].[Country] ([CountryName]) VALUES ('Zimbabwe');
";
            migrationBuilder.Sql(inserts);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            var sql = @"DELETE FROM [app].[Country]";
            migrationBuilder.Sql(sql);
        }
    }
}
