export const Transactions = 'transactions'
export const Authentication = 'authentication'
export const CashWithdrawals = 'cashWithdrawals'
export const Reconcile = 'reconcile'
export const Queries = 'queries'
export const InitialSetup = 'initialSetup'
export const Setup = 'setup'
